import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";

/**
 * Lint configuration.
 *
 * The rules that earn their place here are the ones a reviewer cannot reliably
 * catch by reading. This codebase is almost entirely async, so a dropped
 * promise -- a generation that is never awaited, a status update that races the
 * job it describes -- is both the most likely bug and the least visible one.
 * Type-aware linting is enabled for that reason alone, and it is worth the
 * slower run.
 *
 * Stylistic rules are left to Prettier; eslint-config-prettier turns off
 * everything the formatter already decides so the two never disagree.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/.turbo/**",
      "vendor/**",
      ".venv/**",
      "**/*.d.ts",
      // Generated by the e2e harness at run time.
      "tests/e2e/.tmp/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": [
        "error",
        // A React handler is declared to return void and an async handler
        // returns a promise nobody awaits, which is exactly what an event
        // handler is meant to do. The check that matters -- a promise passed
        // where sequencing was expected -- stays on.
        { checksVoidReturn: { attributes: false } },
      ],
      // An async method implementing an async interface does not have to await
      // anything to be correct, and most of this codebase's methods are that.
      "@typescript-eslint/require-await": "off",
      // An unused argument is often a deliberate part of a signature the
      // implementation does not need; an unused local is not.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // The database returns unknown-shaped rows and zod returns validated
      // ones; template expressions over them are how errors get reported, and
      // the strict form of these rules objects to almost every log line.
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-call": "off",
    },
  },
  {
    // Config and build files sit outside every tsconfig, so there are no types
    // to reason about. Linting them without type information is better than
    // not linting them.
    files: ["**/*.mjs", "**/*.cjs", "*.config.ts", "*.config.js"],
    ...tseslint.configs.disableTypeChecked,
    languageOptions: {
      ...tseslint.configs.disableTypeChecked.languageOptions,
      globals: { ...globals.node, ...globals.browser },
    },
  },
  {
    files: ["apps/**/*.tsx"],
    plugins: { "react-hooks": reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  {
    files: ["tests/**/*.ts", "**/*.spec.ts"],
    rules: {
      // Tests deliberately construct malformed input to prove it is rejected.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  prettier,
);
